# Generated by Django 5.2.6 on 2025-11-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Failed/Cancelled', 'Failed/Cancelled'), ('Success', 'Success')], max_length=20),
        ),
    ]
